import type { ExternalPacket, ExternalFormPlan } from '@ctx/contracts';

/** Every submitted field must be bound to an answer or explicit reviewed constant. */
export function externalFormRequestBody(packet: ExternalPacket, plan: ExternalFormPlan): Record<string, string> | null {
  const r = plan.request;
  if (!r || Object.keys(r.static_fields).length > 100) return null;
  try {
    const url = new URL(r.url), target = new URL(plan.url);
    if (url.protocol !== 'https:' || url.username || url.password || url.hash || url.origin !== target.origin) return null;
  } catch { return null; }
  if (r.answer_fields.length !== packet.answers.length ||
    new Set(r.answer_fields.map(f => f.key)).size !== packet.answers.length ||
    new Set(r.answer_fields.map(f => f.field)).size !== packet.answers.length ||
    new Set(packet.answers.map(a => a.key)).size !== packet.answers.length) return null;
  const entries: [string, string][] = Object.entries(r.static_fields);
  for (const field of r.answer_fields) {
    const answer = packet.answers.find(a => a.key === field.key);
    if (!answer || Object.hasOwn(r.static_fields, field.field)) return null;
    entries.push([field.field, answer.value]);
  }
  return Object.fromEntries(entries);
}

export function externalFormRequestMatches(packet: ExternalPacket, plan: ExternalFormPlan,
  request: { url: string; method: string; content_type: string; body: string | null }): boolean {
  const expected = externalFormRequestBody(packet, plan), r = plan.request;
  if (!expected || !r || request.url !== r.url || request.method !== r.method || !request.body || request.body.length > 512000) return false;
  const type = request.content_type.split(';')[0]?.trim().toLowerCase();
  let actual: Record<string, unknown>;
  try {
    if (r.encoding === 'json') {
      if (type !== 'application/json') return false;
      // Duplicate JSON member names can be interpreted differently by servers.
      // Accept only canonical JSON generated by this declared flat string map.
      actual = JSON.parse(request.body);
      if (!actual || Array.isArray(actual) || typeof actual !== 'object') return false;
      // A flat object of string members has exactly one unescaped colon per pair.
      const tokens = request.body.match(/"(?:[^"\\]|\\.)*"|[^\s]/g) ?? [];
      if (tokens.filter(t => t === ':').length !== Object.keys(actual).length) return false;
    } else {
      if (type !== 'application/x-www-form-urlencoded') return false;
      const entries = [...new URLSearchParams(request.body).entries()];
      if (new Set(entries.map(([key]) => key)).size !== entries.length) return false;
      actual = Object.fromEntries(entries);
    }
  } catch { return false; }
  return Object.keys(actual).length === Object.keys(expected).length &&
    Object.entries(expected).every(([key, value]) => Object.hasOwn(actual, key) && actual[key] === value);
}

export function externalDeclarationKind(question: string): 'process' | 'personal' | null {
  const text = question.normalize('NFKC').replace(/[\u2010-\u2015]/g, '-').replace(/[\u2018\u2019]/g, "'");
  if (/unassisted|(?:your|my|their) own (?:words|responses|answers)|without.{0,60}(?:help|assistance|AI|tools)|third[- ]party (?:sources|tools|assistance)|(?:AI|machine)[- ](?:generated|assisted)|not.{0,40}(?:artificial intelligence|language model)|(?:produced|written|generated).{0,60}(?:tools|assistance)|sin (?:ayuda|asistencia)|sans (?:aide|assistance)|ohne (?:Hilfe|Unterstützung)/i.test(text)) return 'process';
  if (/conflict|confidential|consent|agree|terms|restrict|employ|available|availability|compliance|certif|attest|familiarity|\b[1-5]\s*[-–]\s*[1-5]\b|procurement|decision.maker|current customer|committed spend/i.test(text)) return 'personal';
  return null;
}
